modLoader="javafml" # mandatory
loaderVersion="[43,)"
license="MIT"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="shaded_citadels"
version="${file.jarVersion}"
displayName="Shaded Citadels"
# updateJSONURL="https://change.me.example.invalid/updates.json"
# displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
# logoFile="examplemod.png"
credits="Thanks for this example mod goes to Java"
authors="CAPPIN and DAKRAS"
description='''Deeper and darker!'''

[[dependencies.shaded_citadels]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shaded_citadels]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
